import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Header from "@/components/Header";

const roboto = Roboto({
  weight:['100', '300', '700', '900'],
  subsets: ['latin']
});



export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} antialiased md:overflow-hidden`}
      >
        <Provider>
          <Header/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
